apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-bad
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: w9-api:1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ERROR_RATE
              value: "1.0"
            - name: VERSION
              value: "bad"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
