apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w8-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hunghk43/kimhung-aws-accelerator-p2
    targetRevision: main
    path: cloud/w8/lab

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
